version: "3"
services:
  app:
    container_name: simple-auth
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://username:password@db:5433/database_name?sslmode=disable" # Ganti dengan koneksi database yang sesuai
      SECRET_KEY: "your-secret-key" # Ganti dengan kunci rahasia yang sesuai
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: simple-auth-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
    ports:
      - "5433:5433"
